### ISSUE TITLE
Ao buscar palavras sugeridas pelo google, como "reforma agrária" , a busca não retorna resultados corretos

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#100]
Como simular:
1- Buscar a palavra 'reforma' e notar que a busca retorna alguns post 
2- Digitar o termo 'reforma agrária' (autocomplete do google)
3- Verificar que nao retorna nenhum resultado

**Comment by gabrielcaires** [comment]
No meu o comportamento foi o seguinte:
* Reforma > Retorna resultados
* Reforma agrária > Retorna resultados
* Quando digito reforma e o google autocompleta para reforma-ágraria(acento errado)  ele não mostra nada. 

Será que é isso?

**Comment by TaiseAssis** [comment]
Exatamente isso, @gabrielcaires. Corrigi a descrição. :)

**Comment by RatoX** [comment]
Se retorna resultado com a palavra certa então o problema não existe.

Fechandoooooo!
