### ISSUE TITLE
Corrigir bugs de sumiço de texto, ao editar post .

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#101]
Temos notado que quando editamos um post, o ckeditor pode demorar de carregar o post.. pode ser um indicio da causa do problema salvar antes do conteudo ser carregado.

ver post https://github.com/movimento-sem-terra/site-novo/commits/master/_posts/2014/12/2014-12-16-os-interesses-dos-parlamentares-que-querem-aprovar-a-pec-215.md

**Comment by gabrielcaires** [comment]
Não consegui reproduzir, mesmo assim subi uma versão que "aguarda" o editor ser carregado antes de permitir salvar o post.
Vamos ver se acontece novamente.

**Comment by RatoX** [comment]
A reprodução é meio complicada a melhor forma é usar uma janela anonima.

**Comment by RatoX** [comment]
Nops, ainda não tá funcionando.

**Comment by RatoX** [comment]
Isso é problema com o Marighella:

https://github.com/marighella/cms/issues/56
