### ISSUE TITLE
O post do lançamento sumiu

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#102]
http://www.mst.org.br/2015/01/21/ao-vivo-bate-papo-entre-stedile-e-blogueiros.html

**Comment by gabrielcaires** [comment]
Ele foi parar na data que colocaram no post:

https://raw.githubusercontent.com/movimento-sem-terra/site-novo/3e79903ceeb03be24698631475fb8914db34d550/_posts/2015/01/2015-01-21-ao-vivo-bate-papo-entre-stedile-e-blogueiros.md

Foi para URL:
http://www.mst.org.br/2013/01/04/ao-vivo-bate-papo-entre-stedile-e-blogueiros.html

Talvez seja interessante exibir uma mensagem avisando que, caso a data seja mudada, o endereço do post será modificado, fazendo com que inclusive seja perdido a indexação do endereço (Ou seja a data deve ser mudada só em ultimo caso)

**Comment by RatoX** [comment]
O Nome do arquivo é ( ou deveria ser ) imutavel precisamos descobrir o que tá acontecendo no Marighella.

**Comment by RatoX** [comment]
Esse é um problema que está acontecendo no Marighella.

https://github.com/marighella/cms/issues/58
