### ISSUE TITLE
[Nossa história] Implementar versão desktop : Período I - Dec 70 ate 83

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#103]
Obter o texto de referencia: https://docs.google.com/a/thoughtworks.com/document/d/1BdTwLqyyib9LY9cE-kukbT2AGjCfusKyRLdGnLlRfS8/edit?usp=sharing

Para o psd:
https://drive.google.com/a/thoughtworks.com/folderview?id=0B3hHLI-7YnCSTkt6MjBDR2o4ZkE&usp=sharing

**Comment by mauriciomelo** [comment]
Aeoh

**Comment by TaiseAssis** [comment]
- Trocar a foto do bloco 1981
 - Alterar a frase “A maior manifestação…” para "As ocupações de terra se tornaram ferramenta de expressão camponesa e de contestação do autoritarismo."
 - A  data jul/25 não é relevante para o movimento,  seria interessante troca-la por um ícone com punhos erguidos para simbolizar as marchas.
 - Incluir um bloco para o ano 1982 (incluir a foto da  5ª Romaria da Terra )

**Comment by TaiseAssis** [comment]
- Incluir no final das seções (Encruzilhada, Boletim e Romaria) links para o leitor voltar ao topo da página
- Incluir no final da página, um link para o próximo período ("Surge o MST"
- Incluir o link para o post que fala da Encruzilhada Natalino (http://www.mst.org.br/2014/06/18/a-luta-do-acampamento-encruzilhada-natalino.html)
