### ISSUE TITLE
[Nossa Produção] Criar  a paginação por setor

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#106]
Dado que existem videos e notícias cuja sessão="produção" 
Quando o usuário clicar no botão "Mais notícias" 
Então devemos exibir a página apenas com as notícias cujo setor = produção

**Comment by TaiseAssis** [comment]
Os vídeos estão sendo exibidos sem imagem. 
Tenho dúvidas quanto a melhor forma de exibi-los..

**Comment by TaiseAssis** [comment]
Para os posts tipo vídeo devemos exibir o thumbnail do vídeo.

**Comment by mauriciomelo** [comment]
Coloquei as thumbs dos vídeos, será que é a melhor forma?
http://mst-ba.herokuapp.com/nossa-producao/noticias/
