### ISSUE TITLE
Transfira a responsabilidade de edição do 'pirulito' para o CMS

### ISSUE THREAD

**Issue by mauriciomelo** [movimento-sem-terra/site-novo#113]
Atualmente para editar o pirulito é necessário atualizar um arquivo de configuração do site, entretanto essa é uma parte muito mais relacionada com o conteúdo (responsabilidade do editor/jornalista) do que a com configuração (responsabilidade do dev)

**Comment by TaiseAssis** [comment]
#70 - 
 https://github.com/marighella/cms/issues/70
