### ISSUE TITLE
[Nossa História] - Período III 88 -93 - Implementar versão desktop 

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#121]
Ver o texto de referência:
https://docs.google.com/a/thoughtworks.com/document/d/1dcxJQi_k2GQVcRT1WmFAPBrcmqSwceRAp_xZfVmY2u0/edit?usp=sharing

Protótipo:
https://drive.google.com/a/thoughtworks.com/file/d/0Bys1Dm8h-vmTclZUYzZqZzExNzFnc2NXbWd5RE5pNjE5TWR3/view?usp=sharing

**Comment by TaiseAssis** [comment]
Alterar o texto do período Collor para:
“O neoliberalismo toma conta do país, causando a fragmentação da classe trabalhadora e o avanço do capital.”

**Comment by TaiseAssis** [comment]
Faltou incluir o link para o texto explicativo do Congresso.
"De 8 a 10 de maio de 1990, foi realizado o 2° {Congresso} Nacional do MST,"

**Comment by pmaia** [comment]
Ok. É para usar o mesmo texto que usamos no período anterior?

**Comment by TaiseAssis** [comment]
Yep.. :)
