### ISSUE TITLE
Fazer protótipo 'Nossa História' (Período I e II)

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#31]
A ideia desta página é montar uma linha do tempo e exibir as principais informações sobre os congressos (linhas políticas, conjuntura política, fatos históricos), nossas lutas e conquistas. Importante incluir fotos distribuídas ao longo destes 30 anos de luta e incluir links para outros conteúdos (Nossos objetivos, nossas bandeiras, etc)

Link para o contexto inicial da nossa historia:
https://docs.google.com/a/thoughtworks.com/document/d/1nRkbut8PxHeu6oe4OaSOs6kY0TCxcCSQkqSEVKLtrLM/edit?usp=sharing

**Comment by TaiseAssis** [comment]
Atividade de priorização cos clientes foi confirmada para terça feira

**Comment by TaiseAssis** [comment]
Aguardando o envio do material pra dar continuidade.

**Comment by raonylima** [comment]
Amanhã darei início ao visual da página. Da parte inicial, pelo menos: o menu com as datas, a foto, logo abaixo, e o primeiro tópico.

**Comment by TaiseAssis** [comment]
Texto do primeiro [Período I - Década de 70 até 85] da história foi enviado.

Para ver o texto, fotos e links entrar na pasta: https://drive.google.com/a/thoughtworks.com/folderview?id=0Bys1Dm8h-vmTaVEwVjZsQWU4VTg&usp=drive_web
