### ISSUE TITLE
Alterar o domínio do site atual para antigo.mst.org.br

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#34]

**Comment by jcsfbass** [comment]
Lembrem que terão que gerar um novo id para o Custom Search Engine do Google para a url mst.org.br, senão ele continuará buscando em novo.mst.org.br. Então ele deverá reindexar tudo novamente.

**Comment by TaiseAssis** [comment]
A busca ainda refere-se ao site mst.org.br/node
