### ISSUE TITLE
[Publicações] - Para o leitor pesquisar todas as edições exibir todas as publicações dos Jornais Sem Terra

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#41]
### Critérios
- [ ] Ao clicar no menu Publicacao devemos abrir o link: http://issuu.com/paginadomst
- [ ] Garantir que o link irá abrir em uma outra aba 

Atualmente existem 326 edições do jornal sem terra. Apenas a última está no site atual.

**Comment by pmaia** [comment]
Falei com o @josecoutinhojr e ele me disse que todos os jornais antigos estão no issuu.com. Talvez o esforço seja apenas ver como embarcar o conteúdo que tá lá no site novo.
