### ISSUE TITLE
[Nossos Símbolos] Implementar a página

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#43]
Documento de referência: 
https://docs.google.com/a/thoughtworks.com/document/d/13PgBGHHQn6VAeFjlGWgKE0cn5Ea9ayCR3bydt1Ma01c/edit?usp=sharing

Wireframe : https://drive.google.com/a/thoughtworks.com/file/d/0Bys1Dm8h-vmTU0ZkUXF6U18td1k/view?usp=sharing

Atender a issue #126

**Comment by luizalb** [comment]
Incluir 3 ultimos posts do setor `"Frente de Massa" 
obs. incluir no marighella

**Comment by TaiseAssis** [comment]
Como está a versão para dispositivos móveis?

**Comment by TaiseAssis** [comment]
Moblie - As noticias estão  com o título truncado

**Comment by TaiseAssis** [comment]
Foto Lona Preta: https://drive.google.com/a/thoughtworks.com/file/d/0Bys1Dm8h-vmTMFhyUk15bk5ESGZqMm1oYmNOdlU0V0xQbTdn/view?usp=sharing

**Comment by TaiseAssis** [comment]
O parágrafo inicial da página deve ser:
Desde suas primeiras ocupações, os Sem Terra vêm criando diversos símbolos de representação de sua luta. Circunstanciais, como a cruz da Encruzilhada Natalino, ou permanentes, como a bandeira e o hino do MST, eles são, sobretudo, signos da unidade em torno de um ideal e constituem a mística do Movimento.
