### ISSUE TITLE
Para alguns posts, estamos exibindo a página 404. (reindexacao da pesquisa)

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#78]
Pesquisar pela palavra 'sertao' e vefiricar a última notícia da página:
http://novo.mst.org.br/sitemap.xml

**Comment by pereiragislene** [comment]
Foi necessário confirmar o site no Webmaster Tools do Google. Feito isso, solicitei reindexação de todas as URLs do site.
Pelo que entendi, temos direito a fazer essa solicitação até 10x por mês.

**Comment by pereiragislene** [comment]
Também incluí o nosso sitemap.xml no Google Webmaster Tools.
