### ISSUE TITLE
Implementar a versão desktop "Quem Somos"

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#82]

**Comment by TaiseAssis** [comment]
Alteração na sessão Mística :  exibir o vídeo no lugar da foto atual.
Ainda faltam descrição de 3 setores e 3 fotos das bandeiras.

**Comment by TaiseAssis** [comment]
Luiz enviou outro vídeo para quem somos:
https://www.youtube.com/watch?v=kvKhNUkxfYk&feature=youtu.be

Se o trabalho de alterar isso agora for muito grande, podemos criar outro cartao.

**Comment by TaiseAssis** [comment]
Relações Internacionais 

A política de Relações Internacionais do MST tem como alicerce os valores da solidariedade, do humanismo e do internacionalismo, um legado histórico da classe trabalhadora. Não há fronteiras, geográficas ou étnicas, que devam limitar as lutas contra a exploração do ser humano pelo ser humano. O Coletivo de Relações Internacionais (CRI) do MST tem o papel de articular a solidariedade às nossa lutas, contribuir com as lutas de todos os povos e despertar e aprimorar, junto à nossa base social, os valores que nos fazem mais humanos e solidários, construtores de uma sociedade socialista.

**Comment by TaiseAssis** [comment]
Retirar a Forma de Luta 'Produção' (é um setor)

**Comment by raonylima** [comment]
Gabriel, vou colar aqui o que conversamos: o texto "Além disso..." tá com uma largura muito grande. texto com muitas palavras na horizontal não costumam ser fáceis de ler. acho que vale testar alinhar ele: do início do primeiro círculo até o fim do último.

**Comment by TaiseAssis** [comment]
Conversaremos com o Luiz na sexta sobre a página.
