### ISSUE TITLE
Implementar versão desktop de "Nossa Produção"

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#85]
[Saiba como nossa produção mudou histórias]
- Exibir 2 últimas notícias cujo label = "special-stories" e sector= "production" 

[Ultimas notícias] 
- Exibir as 4 últimas notícias cujo sector= "production" (a notícia n deve estar em nenhuma outra sessão da página)
 
[Fique de Olho"]
- Exibir a última notícia cuja section = "cover" e sector= "production"

[Videos]
- Exibir 2 notícias cuja section = "tv" e sector= "production"

[ Conheça mais sobre o MST]  (no lugar de Conheça o nosso histórico):
- Nossa história - abrir a página "Nossa Historia" (em construção)
- Objetivos - Abrir a página "Quem somos" na parte de "Objetivos"
- Via Campesina = abrir em outra aba a página da Via Campesina (http://viacampesina.org/en/)

Para ver o conteúdo e fotos selecionadas :
https://docs.google.com/a/thoughtworks.com/document/d/1YE7hHUc1uHNsqWn3AXZnq-v54vyQZq6dmk2D6p_ovS4/edit?usp=sharing

**Comment by gabrielcaires** [comment]
Link ainda sem as notícias "verdadeiras"
http://mst-ba.herokuapp.com/nossa-producao/

**Comment by TaiseAssis** [comment]
Na sessão "Pelo Brasil" exibiremos links para posts das sessão vídeo.  A imagem de capa será o thumbnail do vídeo, que abrirá o post ao ser clicada .

**Comment by mauriciomelo** [comment]
Quais noticias devem aparecer na sessão  "Conheça nosso histórico"?

**Comment by TaiseAssis** [comment]
Objetivos - Abrir a página "Quem somos" na parte de "Objetivos"
Reforma Agrária = página da Via Campesina (ainda não construída)

**Comment by TaiseAssis** [comment]
Incluir 96 agroindústrias nos dados demográficos 
Brasil ::  100 cooperativas; 96 agroindústrias; 1,9 mil associações; 350 mil famílias assentadas

**Comment by gabrielcaires** [comment]
Em "Conheça nosso histórico", falei com o Raony e ficamos de conversar sobre o que fazer as thumbs que indicam esses links, especialmente por Nossa Historia e Via Campesina não terem links certos.

Por hora deixamos 2 notícias aleatórias.

**Comment by TaiseAssis** [comment]
As 'ultimas notícias' e os videos já estão com o setor = 'producao'.. Mas é preciso fazer um ajuste para exibir apenas 4 noticias em "Ultimas notícias"

**Comment by TaiseAssis** [comment]
A sessao [Fique de Olho] - também já possui uma notícia para ser exibida na pagina

**Comment by TaiseAssis** [comment]
Aguardando as legendas das fotos.

**Comment by TaiseAssis** [comment]
Foi decidido que a página irá ao ar sem as legendas/créditos das fotos.
