### ISSUE TITLE
[Discussão] Posts Relacionados

### ISSUE THREAD

**Issue by gabrielcaires** [movimento-sem-terra/site-novo#86]
Em um spike, testamos a geração de posts relacionados filtrando somente pela sua sessão. Percebemos uma melhora no tempo de processamento do Jekyll. Porém essa mudança afeta o resultado exibido. Vamos discutir essa mudança amanhã na Standup!

**Comment by RatoX** [comment]
Estamos trabalhando para a geração de posts relacionados seja feita no Marighella não mais no site.

**Comment by RatoX** [comment]
https://github.com/marighella/cms/issues/39
