### ISSUE TITLE
Corrigir a reportagem especial que não está indo para a sessão correta.

### ISSUE THREAD

**Issue by TaiseAssis** [movimento-sem-terra/site-novo#93]
Postagem incorreta: http://www.mst.org.br/2015/01/15/cooperacao-agricola-o-simbolo-do-assentamento-conquista-na-fronteira.html

**Comment by RatoX** [comment]
O Carousel tem prioridade, o que está acontecendo é que a noticia tá aparecendo primeiro lá para depois cair para a sessão correta. 
![screen shot 2015-01-20 at 10 29 53 am](https://cloud.githubusercontent.com/assets/3452187/5817901/53dae72e-a08f-11e4-9667-90409deafc4c.png)
